let g:carbon_now_sh_options = {
\  'ln': 'true',
\  'fm': 'IBM Plex Mono',
\  'bg': 'rgba(74,144,226,1)',
\  't': 'night-owl',
\  'wt': 'none',
\  'l': 'auto',
\  'ds': 'true',
\  'dsyoff': '20px',
\  'dsblur': '68px',
\  'wc': 'true',
\  'wa': 'true',
\  'pv': '56px',
\  'ph': '56px',
\  'ln': 'false',
\  'fm': 'IBM Plex Mono',
\  'fs': '14.5px',
\  'lh': '141%',
\  'si': 'false',
\  'es': '2x',
\  'wm': 'false'
\}
